WebDiDong/Models/GioHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int IdGH { get; set; }
        public string MaTaiKhoan { get; set; }
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> TongTien { get; set; }
    }
}

WebDiDong/Models/LoaiSanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSanPham()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaLoaiSanPham { get; set; }
        public string TenLoaiSanPham { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}

WebDiDong/Models/NhaSanXuat.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaSanXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaSanXuat()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaNhaSanXuat { get; set; }
        public string TenNhaSanXuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}

WebDiDong/Models/ThongTinCaNhan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCaNhan
    {
        public int id { get; set; }
        public string MaTaiKhoan { get; set; }
        public string TenTaiKhoan { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string GioiTinh { get; set; }
        public string NgaySinh { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}

WebDiDong/Controllers/GioHangController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDiDong.Models;
using WebDiDong.Models.BUS;

namespace WebDiDong.Controllers
{
    [Authorize]
    public class GioHangController : Controller
    {
        //
        // GET: /GioHang/
        public ActionResult Index()
        {
            ViewBag.TongTien = GioHangBUS.TongTien(User.Identity.GetUserId());
            DBDiDongEntities db = new DBDiDongEntities();
            var matk = User.Identity.GetUserId();
            List<GioHang> gioHangs = db.GioHangs.Where<GioHang>(row => row.MaTaiKhoan == matk).ToList();
            using (var sl = new DBDiDongEntities())
            {
                var soluong = sl.Database.SqlQuery<int>("select count(SoLuong) from GioHang where MaTaiKhoan = '" + matk + "'").FirstOrDefault();
                ViewBag.TongSoLuong = soluong;
            }
            return View(gioHangs);
        }

        [HttpPost]
        public ActionResult Them(int masanpham, int soluong, int gia, string tensanpham)
        {
            try
            {
                GioHangBUS.Them(masanpham, User.Identity.GetUserId(), soluong, gia, tensanpham);
                return RedirectToAction("index");
            }
            catch
            {
                return RedirectToAction("../Shop/index");
            }

        }

        [HttpPost]
        public ActionResult CapNhat(int masanpham, int soluong, int gia, string tensanpham)
        {
            try
            {
                GioHangBUS.CapNhat(masanpham, User.Identity.GetUserId(), soluong, gia, tensanpham);
                return RedirectToAction("index");
            }
            catch
            {
                return RedirectToAction("../Shop/index");
            }

        }

        [HttpGet]
        public ActionResult Xoa(int masanpham)
        {
            try
            {
                GioHangBUS.Xoa(masanpham, User.Identity.GetUserId());
                return RedirectToAction("index");
            }
            catch
            {
                return RedirectToAction("../Shop/index");
            }

        }
    }
}

WebDiDong/Controllers/LoaiSanPhamController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDiDong.Models;
using WebDiDong.Models.BUS;

namespace WebDiDong.Controllers
{
    public class LoaiSanPhamController : Controller
    {
        // GET: LoaiSanPham
        public ActionResult Index(int id, int page = 1, int pagesize = 6)
        {
            var ds = LoaiSanPhamBUS.ChiTiet(id).ToPagedList(page, pagesize);
            using (var br = new DBDiDongEntities())
            {
                string loai = br.Database.SqlQuery<string>("select TenLoaiSanPham from LoaiSanPham where MaLoaiSanPham = " + id + "").FirstOrDefault();
                ViewBag.loai = loai;
            }
            return View(ds);
        }
    }
}

WebDiDong/Controllers/NhaSanXuatController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDiDong.Models;
using WebDiDong.Models.BUS;

namespace WebDiDong.Controllers
{
    public class NhaSanXuatController : Controller
    {
        // GET: NhaSanXuat
        public ActionResult Index(int id, int page = 1, int pagesize = 6)
        {
            var ds = NhaSanXuatBUS.ChiTiet(id).ToPagedList(page, pagesize);
            using (var br = new DBDiDongEntities())
            {
                string brand = br.Database.SqlQuery<string>("select TenNhaSanXuat from NhaSanXuat where MaNhaSanXuat = " + id + "").FirstOrDefault();
                ViewBag.Brand = brand;
            }
            return View(ds);
        }
    }
}

WebDiDong/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDiDong.Models;
using PagedList;

namespace WebDiDong.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index(int page = 1, int pagesize = 6)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            List<SanPham> sanPhams = db.SanPhams.ToList();
            return View(sanPhams.ToPagedList(page, pagesize));
        }

        // GET: Shop/Details/5
        public ActionResult Details(int id)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            SanPham sp = db.SanPhams.Where(row => row.MaSanPham == id).FirstOrDefault();
            return View(sp);
        }

        // GET: Shop/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shop/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shop/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Shop/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shop/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Shop/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebDiDong/Controllers/ThongTinCaNhanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WebDiDong.Models;
using WebDiDong.Models.BUS;

namespace WebDiDong.Controllers
{
    public class ThongTinCaNhanController : Controller
    {
        [Authorize]
        // GET: ThongTinCaNhan
        public ActionResult Index()
        {
            var ds = ThongTinCaNhanBUS.LoadThongTin(User.Identity.GetUserId());
            return View(ds);
        }
        public ActionResult Them()
        {
            DBDiDongEntities db = new DBDiDongEntities();

            ViewBag.GioiTinh = db.ThongTinCaNhans.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Them(ThongTinCaNhan ttcn)
        {
            try
            {
                int IsInserted = 0;
                DBDiDongEntities db = new DBDiDongEntities();
                db.ThongTinCaNhans.Add(ttcn);
                IsInserted = db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebDiDong/Views/Shared/Image.cshtml
@model string
<td><img style="width: 50%;" src="~/Asset/images/@Model" /></td>

WebDiDong/Views/Shared/_Footer.cshtml
<footer>
    <div class="container">
        <div class="wrap-footer">
            <div class="row">
                <div class="col-md-3 col-footer footer-1">
                    <img src="~/Asset/images/logofooter.png" />
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                </div>
                <div class="col-md-3 col-footer footer-2">
                    <div class="heading"><h4>Customer Service</h4></div>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Delivery Information</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms & Conditions</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-footer footer-3">
                    <div class="heading"><h4>My Account</h4></div>
                    <ul>
                        <li><a href="#">My Account</a></li>
                        <li><a href="#">Brands</a></li>
                        <li><a href="#">Gift Vouchers</a></li>
                        <li><a href="#">Specials</a></li>
                        <li><a href="#">Site Map</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-footer footer-4">
                    <div class="heading"><h4>Contact Us</h4></div>
                    <ul>
                        <li><span class="glyphicon glyphicon-home"></span>California, United States 3000009</li>
                        <li><span class="glyphicon glyphicon-earphone"></span>+91 8866888111</li>
                        <li><span class="glyphicon glyphicon-envelope"></span>infor@yoursite.com</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    Your Store 10 2022 - Designed by <a href="#">Group12</a>
                </div>
                <div class="col-md-6">
                    <div class="pull-right">
                        <ul>
                            <li><img src="~/Asset/images/visa-curved-32px.png" /></li>
                            <li><img src="~/Asset/images/paypal-curved-32px.png" /></li>
                            <li><img src="~/Asset/images/discover-curved-32px.png" /></li>
                            <li><img src="~/Asset/images/maestro-curved-32px.png" /></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

WebDiDong/Views/Shared/_GioHang.cshtml
@model IEnumerable<WebDiDong.Models.GioHang>

    <div class="col-md-4" style="float:right">
        <div id="cart"><a class="btn btn-1" href="@Url.Action("Index", "GioHang")"><span class="glyphicon glyphicon-shopping-cart"></span>CART : @Model.Count() ITEM</a></div>
    </div>

WebDiDong/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Mobile Shop</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="~/Asset/css/bootstrap.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Asset/css/style.css">


    <!-- Custom Fonts -->
    <link rel="stylesheet" href="~/Asset/font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Asset/fonts/font-slider.css" type="text/css">

    <!-- jQuery and Modernizr-->
    <script src="~/Asset/js/jquery-2.1.1.js"></script>

    <!-- Core JavaScript Files -->
    <script src="~/Asset/js/bootstrap.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
    <![endif]-->
    <style>
        .ck.ck-content ul,
        .ck.ck-content ul li {
            list-style-type: inherit;
        }

        .ck.ck-content ul {
            /* Default user agent stylesheet, you can change it to your needs. */
            padding-left: 40px;
        }
    </style>
</head>

<body>
    <!--Top-->
    <nav id="top">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <select class="language">
                        <option value="English" selected>English</option>
                        <option value="France">France</option>
                        <option value="Germany">Germany</option>
                    </select>
                    <span class="currency"><a href="/Admin/MainAdmin">Đến trang Admin</a></span>
                </div>
                <div class="col-xs-6">
                    <ul class="top-link">
                        @Html.Partial("_LoginPartial", WebDiDong.Models.BUS.ThongTinCaNhanBUS.LoadThongTin(User.Identity.GetUserId()))
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!--Header-->
    <header class="container">
        <div class="row">
            <div class="col-md-4">
                <div id="logo"><a href="/Home"><img src="~/Asset/images/logo.png" /></a></div>
            </div>
            <div class="col-md-4">
                <form class="form-search" action="~/TimKiem/KetQuaTimKiem">
                    <input type="text" class="input-medium search-query" name="search" placeholder="Nhập tên sản phẩm" value="@ViewBag.Search">
                    <button type="submit" class="btn"><span class="glyphicon glyphicon-search"></span></button>
                </form>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                @Html.Partial("_GioHang", WebDiDong.Models.BUS.GioHangBUS.DanhSach(User.Identity.GetUserId()));
            }
        </div>
    </header>

    <!--Navigation-->
    <nav id="menu" class="navbar bg-gradient-dark">
        <div class="container">
            <div class="navbar-header">
                <span id="heading" class="visible-xs">Categories</span>
                <button type="button" class="btn btn-navbar navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>
                        @Html.ActionLink("Sản Phẩm", "Index", "Shop")
                    </li>
                    @Html.Partial("_LoaiSanPham", WebDiDong.Models.BUS.LoaiSanPhamBUS.DanhSach())
                    @Html.Partial("_NhaSanXuat", WebDiDong.Models.BUS.NhaSanXuatBUS.DanhSach())
                </ul>
            </div>
        </div>
    </nav>
    <!--//////////////////////////////////////////////////-->
    <!--///////////////////HomePage///////////////////////-->
    <!--//////////////////////////////////////////////////-->
    @RenderBody()
    @{ Html.RenderPartial("_Footer");}

    @RenderSection("scripts", required: false)
</body>
</html>

WebDiDong/Views/Shared/_LoaiSanPham.cshtml
@model IEnumerable<WebDiDong.Models.LoaiSanPham>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Loại</a>
    <div class="dropdown-menu">
        <div class="dropdown-inner">
            <ul class="list-unstyled">
                @foreach (var item in Model)
                {
                    <li><a href="@Url.Action("Index","LoaiSanPham", new { id = @item.MaLoaiSanPham})">@item.TenLoaiSanPham</a></li>
                }
            </ul>
        </div>
    </div>
</li>

WebDiDong/Views/Shared/_NhaSanXuat.cshtml
@model IEnumerable<WebDiDong.Models.NhaSanXuat>


    

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hãng</a>
    <div class="dropdown-menu">
        <div class="dropdown-inner">
            <ul class="dropdown-divider">
                @foreach (var item in Model.Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }
            </ul>

            <ul class="dropdown-divider">
                @foreach (var item in Model.Skip(5).Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }

            </ul>
            <ul class="dropdown-divider">
                @foreach (var item in Model.Skip(10).Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }
            </ul>
            <ul class="dropdown-divider">
                @foreach (var item in Model.Skip(15).Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }
            </ul>
            <ul class="dropdown-divider">
                @foreach (var item in Model.Skip(20).Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }
            </ul>
            <ul class="dropdown-divider">
                @foreach (var item in Model.Skip(25).Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }
            </ul>
            <ul class="dropdown-divider">
                @foreach (var item in Model.Skip(30).Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }
            </ul>
            <ul class="dropdown-divider">
                @foreach (var item in Model.Skip(35).Take(5))
                {
                    <li>
                        <a href="@Url.Action("Index", "NhaSanXuat", new { id = @item.MaNhaSanXuat })">@item.TenNhaSanXuat</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</li>

WebDiDong/Views/Shared/_ThongTinCaNhan.cshtml
@model  IEnumerable<WebDiDong.Models.ThongTinCaNhan>
@if(Model.Count() ==0)
{
    <a href="@Url.Action("Them","ThongTinCaNhan")">[Thêm mới thông tin]</a>
}
else
{
    <a href="@Url.Action("Index","ThongTinCaNhan")">[Đến Trang Cá Nhân]</a>
}

WebDiDong/Views/Shared/_Top4New.cshtml
@model IEnumerable<WebDiDong.Models.SanPham>

    <div class="row">
        <div class="col-lg-12">
            <div class="heading"><h2>Sản Phẩm Mới</h2></div>
            <div class="products">
                @foreach (var item in Model)
                {
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="product">
                            <div class="image"><a href="@Url.Action("Details","Shop", new { id = @item.MaSanPham})"><img style="width: 250px; height: 250px" src="~/Asset/images/@item.HinhChinh" /></a></div>
                            <div class="buttons">
                                @using (Html.BeginForm("Them", "GioHang", FormMethod.Post))
                                {
                                    <input type="hidden" name="tensanpham" value="@item.TenSanPham" />
                                    <input type="hidden" name="masanpham" value="@item.MaSanPham" />
                                    <input type="hidden" value="1" name="soluong" />
                                    <input type="hidden" name="gia" value="@item.Gia" />
                                    <input type="submit" class="btn btn-2" value="Thêm vào giỏ">
                                }
                                <a class="btn wishlist" href="#"><span class="glyphicon glyphicon-heart"></span></a>
                                <a class="btn compare" href="#"><span class="glyphicon glyphicon-transfer"></span></a>
                            </div>
                            <div class="caption">
                                <div class="name"><h3><a href="@Url.Action("Details","Shop", new { id = @item.MaSanPham})">@item.TenSanPham</a></h3></div>
                                <div class="price text-danger">@String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:0,0}", item.Gia) VNĐ</div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

WebDiDong/Views/Shared/_TopHot.cshtml
@model IEnumerable<WebDiDong.Models.SanPham>

<div class="row">
    <div class="col-lg-12">
        <div class="heading"><h2>Sản Phẩm Hot</h2></div>
        <div class="products">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="product">
                        <div class="image"><a href="@Url.Action("Details","Shop", new { id = @item.MaSanPham})"><img style="width: 250px; height: 250px" src="~/Asset/images/@item.HinhChinh" /></a></div>
                        <div class="buttons">
                            @using (Html.BeginForm("Them", "GioHang", FormMethod.Post))
                            {
                                <input type="hidden" name="tensanpham" value="@item.TenSanPham" />
                                <input type="hidden" name="masanpham" value="@item.MaSanPham" />
                                <input type="hidden" value="1" name="soluong" />
                                <input type="hidden" name="gia" value="@item.Gia" />
                                <input type="submit" class="btn btn-2" value="Thêm vào giỏ">
                            }                            <a class="btn wishlist" href="#"><span class="glyphicon glyphicon-heart"></span></a>
                            <a class="btn compare" href="#"><span class="glyphicon glyphicon-transfer"></span></a>
                        </div>
                        <div class="caption">
                            <div class="name"><h3><a href="@Url.Action("Details","Shop", new { id = @item.MaSanPham})">@item.TenSanPham</a></h3></div>
                            <div class="price text-danger">@String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:0,0}", item.Gia) VNĐ</div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>