WebDiDong/Areas/Admin/Controllers/LoaiSanPhamAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDiDong.Models;

namespace WebDiDong.Areas.Admin.Controllers
{
    public class LoaiSanPhamAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/LoaiSanPham
        public ActionResult Index(string search = "", int page = 1)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            List<LoaiSanPham> loaiSanPhams = db.LoaiSanPhams.Where<LoaiSanPham>(row => row.TenLoaiSanPham.Contains(search)).ToList();
            ViewBag.Search = search;
            if (loaiSanPhams.Count == 0)
            {
                TempData["InfoMessage"] = "Currently products not available in the Database.";
            }

            //Paging
            int NoOfRecordPerPage = 6;
            int NoOfPages = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(loaiSanPhams.Count) / Convert.ToDouble(NoOfRecordPerPage)));
            int NoOfRecordToSkip = (page - 1) * NoOfRecordPerPage;
            ViewBag.Page = page;
            ViewBag.NoOfPages = NoOfPages;
            loaiSanPhams = loaiSanPhams.Skip(NoOfRecordToSkip).Take(NoOfRecordPerPage).ToList();

            return View(loaiSanPhams);
        }

        // GET: Admin/LoaiSanPham/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/LoaiSanPham/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSanPham/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham lsp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int IsInserted = 0;
                    DBDiDongEntities db = new DBDiDongEntities();
                    db.LoaiSanPhams.Add(lsp);
                    IsInserted = db.SaveChanges();
                    if (IsInserted == 1)
                    {
                        TempData["SuccessMessage"] = "Bạn đã thêm thành công...!";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Product is already available/ Unable to save the product details.";
                    }
                }

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/LoaiSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Where<LoaiSanPham>(row => row.MaLoaiSanPham == id).FirstOrDefault();
            if (loaiSanPham == null)
            {
                TempData["InfoMessage"] = "Product not available with ID " + id.ToString();
                return RedirectToAction("Index");
            }
            return View(loaiSanPham);
        }

        // POST: Admin/LoaiSanPham/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, LoaiSanPham lsp)
        {
            try
            {
                int IsUpdate = 0;
                DBDiDongEntities db = new DBDiDongEntities();
                LoaiSanPham loaiSanPham = db.LoaiSanPhams.Where<LoaiSanPham>(row => row.MaLoaiSanPham == lsp.MaLoaiSanPham).FirstOrDefault();

                loaiSanPham.MaLoaiSanPham = lsp.MaLoaiSanPham;
                loaiSanPham.TenLoaiSanPham = lsp.TenLoaiSanPham;

                IsUpdate = db.SaveChanges();
                if (IsUpdate == 1)
                {
                    TempData["SuccessMessage"] = "Bạn đã cập nhật thành công...!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Product is already available/ Unable to update the product details.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/LoaiSanPham/Delete/5
        public ActionResult Delete(int id)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            LoaiSanPham loaiSanPham = db.LoaiSanPhams.Where<LoaiSanPham>(row => row.MaLoaiSanPham == id).FirstOrDefault();
            if (loaiSanPham == null)
            {
                TempData["InfoMessage"] = "Product not available with ID " + id.ToString();
                return RedirectToAction("Index");
            }
            return View(loaiSanPham);
        }

        // POST: Admin/LoaiSanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, LoaiSanPham lsp)
        {
            try
            {
                int IsDeleted = 0;
                DBDiDongEntities db = new DBDiDongEntities();
                LoaiSanPham loaiSanPham = db.LoaiSanPhams.Where<LoaiSanPham>(row => row.MaLoaiSanPham == id).FirstOrDefault();
                db.LoaiSanPhams.Remove(loaiSanPham);
                IsDeleted = db.SaveChanges();
                if (IsDeleted == 1)
                {
                    TempData["SuccessMessage"] = "Bạn đã xóa thành công...!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Product is already available/ Unable to update the product details.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }
    }
}

WebDiDong/Areas/Admin/Views/LoaiSanPhamAdmin/Create.cshtml
@model WebDiDong.Models.LoaiSanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<style>

    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>
<div style="margin:auto;">
    @using (Html.BeginForm("Create", "LoaiSanPhamAdmin", FormMethod.Post, new { @style = "width : 50%; margin: auto;" }))
    {
        @*<label for="fname">Mã Loại Sản Phẩm</label>
            <input type="text" id="fname" name="MaNhaSanXuat" placeholder="Mã Loại Sản Phẩm.." value="@Model.MaLoaiSanPham" />*@

        <label for="lname">Tên Loại Sản Phẩm</label>
        <input type="text" id="lname" name="TenLoaiSanPham" placeholder="Nhập tên loại..." required />

        <center>
            <button type="submit" class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px; ">Create</button>
            <a href="@Url.Action("Index", "LoaiSanPhamAdmin")" class="btn btn-info">Cancel</a>
        </center>
    }
</div>

WebDiDong/Areas/Admin/Views/LoaiSanPhamAdmin/Delete.cshtml
@model WebDiDong.Models.LoaiSanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
<div class="container">
    <h4>Bạn có muốn xóa ?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã loại sản phẩm:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaLoaiSanPham)
        </dd>

        <dt>
            Tên loại sản phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenLoaiSanPham)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <center>
                <button type="submit" class="btn btn-danger" style="margin-top: 20px; margin-bottom: 20px; ">Delete</button>
                <a href="@Url.Action("Index", "LoaiSanPhamAdmin")" class="btn btn-info" style="margin-top: 20px; margin-bottom: 20px; ">Cancel</a>
            </center>
        </div>
    }
</div>

WebDiDong/Areas/Admin/Views/LoaiSanPhamAdmin/Edit.cshtml
@model WebDiDong.Models.LoaiSanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
<style>

    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>

<div style="margin:auto;">
    @using (Html.BeginForm("Edit", "LoaiSanPhamAdmin", FormMethod.Post, new { @style = "width : 50%; margin: auto;" }))
    {
        <label for="fname">Mã Loại Sản Phẩm</label>
        <input type="text" id="fname" name="MaLoaiSanPham" placeholder="Mã loại.." required value="@Model.MaLoaiSanPham" readonly>

        <label for="lname">Tên Loại Sản Phẩm</label>
        <input type="text" id="lname" name="TenLoaiSanPham" placeholder="Tên loại.." required value="@Model.TenLoaiSanPham">

        <center>
            <button type="submit" class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px; ">Save</button>
            <a href="@Url.Action("Index", "LoaiSanPhamAdmin")" class="btn btn-info">Cancel</a>
        </center>
    }
</div>

WebDiDong/Areas/Admin/Views/LoaiSanPhamAdmin/Index.cshtml
@model IEnumerable<WebDiDong.Models.LoaiSanPham>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["InfoMessage"] != null)
{
    <div class="alert alert-info">
        <strong>Information : </strong> @TempData["InfoMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
else if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        <strong>Success ! </strong> @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
else if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Loại Sản Phẩm</h6>
    </div>
    <form style="margin-left: 49px; margin-top: 27px;">
        <label for="search"></label>
        <input type="search"
               class="form-control"
               id="search"
               name="search"
               placeholder="Search"
               style="width: 200px; display: inline;"
               value="@ViewBag.Search" />
        <button type="submit" class="btn btn-primary mx-2">Go</button>
    </form>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã loại sản phẩm</th>
                        <th>Tên loại sản phẩm</th>
                        <th class="text-center" colspan="2">
                            <a href="@Url.Action("Create","LoaiSanPhamAdmin")"><img src="~/Asset/images/Add.png" /></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaLoaiSanPham</td>
                            <td>@item.TenLoaiSanPham</td>
                            <td class="text-center" colspan="2">
                                <a href="@Url.Action("Edit","LoaiSanPhamAdmin", new { id = @item.MaLoaiSanPham})"> <img src="~/Asset/images/edit.png" /></a> &nbsp;&nbsp;
                                <a href="@Url.Action("Delete","LoaiSanPhamAdmin", new { id = @item.MaLoaiSanPham})"> <img src="~/Asset/images/Delete.png" /></a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>



    @{
        int PrevPage = ViewBag.Page - 1;
        if (PrevPage <= 0)
        {
            PrevPage = 1;
        }
        int NextPage = ViewBag.Page + 1;
        if (NextPage > ViewBag.NoOfPages)
        {
            NextPage = ViewBag.NoOfPages;
        }
    }


    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link" href="/Admin/LoaiSanPhamAdmin?page=@PrevPage&search=@ViewBag.Search">
                <<
            </a>
        </li>
        @for (int i = 0; i < ViewBag.NoOfPages; i++)
        {
            if (i + 1 == ViewBag.Page)
            {
                <li class="page-item active">
                    <a class="page-link" href="/Admin/LoaiSanPhamAdmin?page=@(i+1)&search=@ViewBag.Search">
                        @(i + 1)
                    </a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="/Admin/LoaiSanPhamAdmin?page=@(i+1)&search=@ViewBag.Search">
                        @(i + 1)
                    </a>
                </li>
            }
        }
        <li class="page-item">
            <a class="page-link" href="/Admin/LoaiSanPhamAdmin?page=@NextPage&search=@ViewBag.Search">
                >>
            </a>
        </li>
    </ul>
</div>