WebDiDong/Areas/Admin/Controllers/NhaSanXuatAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDiDong.Models;

namespace WebDiDong.Areas.Admin.Controllers
{
    public class NhaSanXuatAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/NhaSanXuat
        public ActionResult Index(string search = "", int page = 1)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            List<NhaSanXuat> nsx = db.NhaSanXuats.Where<NhaSanXuat>(row => row.TenNhaSanXuat.Contains(search)).ToList();
            ViewBag.Search = search;
            if (nsx.Count == 0)
            {
                TempData["InfoMessage"] = "Currently products not available in the Database.";
            }

            //Paging
            int NoOfRecordPerPage = 6;
            int NoOfPages = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(nsx.Count) / Convert.ToDouble(NoOfRecordPerPage)));
            int NoOfRecordToSkip = (page - 1) * NoOfRecordPerPage;
            ViewBag.Page = page;
            ViewBag.NoOfPages = NoOfPages;
            nsx = nsx.Skip(NoOfRecordToSkip).Take(NoOfRecordPerPage).ToList();

            return View(nsx);
        }

        // GET: Admin/NhaSanXuat/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/NhaSanXuat/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhaSanXuat/Create
        [HttpPost]
        public ActionResult Create(NhaSanXuat nsx)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    int IsInserted = 0;
                    DBDiDongEntities db = new DBDiDongEntities();
                    db.NhaSanXuats.Add(nsx);
                    IsInserted = db.SaveChanges();
                    if (IsInserted == 1)
                    {
                        TempData["SuccessMessage"] = "Bạn đã thêm thành công...!";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Product is already available/ Unable to save the product details.";
                    }
                }
                
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/NhaSanXuat/Edit/5
        public ActionResult Edit(int id)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            NhaSanXuat nhaSanXuat = db.NhaSanXuats.Where<NhaSanXuat>(row => row.MaNhaSanXuat == id).FirstOrDefault();
            if(nhaSanXuat == null)
            {
                TempData["InfoMessage"] = "Product not available with ID " + id.ToString();
                return RedirectToAction("Index");
            }
            return View(nhaSanXuat);
        }

        // POST: Admin/NhaSanXuat/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, NhaSanXuat nsx)
        {
            try
            {
                int IsUpdate = 0;
                DBDiDongEntities db = new DBDiDongEntities();
                NhaSanXuat nhaSanXuat = db.NhaSanXuats.Where<NhaSanXuat>(row => row.MaNhaSanXuat == nsx.MaNhaSanXuat).FirstOrDefault();

                nhaSanXuat.MaNhaSanXuat = nsx.MaNhaSanXuat;
                nhaSanXuat.TenNhaSanXuat = nsx.TenNhaSanXuat;
                IsUpdate = db.SaveChanges();
                if (IsUpdate == 1)
                {
                    TempData["SuccessMessage"] = "Bạn đã cập nhật thành công...!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Product is already available/ Unable to update the product details.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/NhaSanXuat/Delete/5
        public ActionResult Delete(int id)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            NhaSanXuat nhaSanXuat = db.NhaSanXuats.Where<NhaSanXuat>(row => row.MaNhaSanXuat == id).FirstOrDefault();
            if (nhaSanXuat == null)
            {
                TempData["InfoMessage"] = "Product not available with ID " + id.ToString();
                return RedirectToAction("Index");
            }
            return View(nhaSanXuat);
        }

        // POST: Admin/NhaSanXuat/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, NhaSanXuat nsx)
        {
            try
            {
                int IsDeleted = 0;
                DBDiDongEntities db = new DBDiDongEntities();
                NhaSanXuat nhaSanXuat = db.NhaSanXuats.Where<NhaSanXuat>(row => row.MaNhaSanXuat == id).FirstOrDefault();
                db.NhaSanXuats.Remove(nhaSanXuat);
                IsDeleted = db.SaveChanges();
                if (IsDeleted == 1)
                {
                    TempData["SuccessMessage"] = "Bạn đã xóa thành công...!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Product is already available/ Unable to update the product details.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }
    }
}

WebDiDong/Areas/Admin/Views/NhaSanXuatAdmin/Create.cshtml
@model WebDiDong.Models.NhaSanXuat

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<style>

    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>
<div style="margin:auto;">
    @using (Html.BeginForm("Create", "NhaSanXuatAdmin", FormMethod.Post, new { @style = "width : 50%; margin: auto;" }))
    {
        @*<label for="fname">Mã Nhà Sản Xuất</label>
            <input type="text" id="fname" name="MaNhaSanXuat" placeholder="Mã Nhà Sản Xuất.." value="@Model.MaNhaSanXuat" />*@

        <label for="lname">Tên Nhà Sản Xuất</label>
        <input type="text" id="lname" name="TenNhaSanXuat" placeholder="Nhập tên nhà sản xuất..." required />

        <center>
            <button type="submit" class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px; ">Create</button>
            <a href="@Url.Action("Index", "NhaSanXuatAdmin")" class="btn btn-info">Cancel</a>
        </center>
    }
</div>

WebDiDong/Areas/Admin/Views/NhaSanXuatAdmin/Delete.cshtml
@model WebDiDong.Models.NhaSanXuat

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
<div class="container">
    <h4>Bạn có muốn xóa ?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã nhà sản xuất:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNhaSanXuat)
        </dd>

        <dt>
            Tên nhà sản xuất
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNhaSanXuat)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <center>
                <button type="submit" class="btn btn-danger" style="margin-top: 20px; margin-bottom: 20px; ">Delete</button>
                <a href="@Url.Action("Index", "NhaSanXuatAdmin")" class="btn btn-info" style="margin-top: 20px; margin-bottom: 20px; ">Cancel</a>
            </center>
        </div>
    }
</div>

WebDiDong/Areas/Admin/Views/NhaSanXuatAdmin/Edit.cshtml
@model WebDiDong.Models.NhaSanXuat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
<style>

    input[type=text] {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }
</style>

<div style="margin:auto;">
    @using (Html.BeginForm("Edit", "NhaSanXuatAdmin", FormMethod.Post, new { @style = "width : 50%; margin: auto;" }))
    {
        <label for="fname">Mã Nhà Sản Xuất</label>
        <input type="text" id="fname" name="MaNhaSanXuat" placeholder="Mã Nhà Sản Xuất.." required value="@Model.MaNhaSanXuat" readonly>

        <label for="lname">Tên Nhà Sản Xuất</label>
        <input type="text" id="lname" name="TenNhaSanXuat" placeholder="Tên Nhà Sản Xuất.." required value="@Model.TenNhaSanXuat">

        <center>
            <button type="submit" class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px; ">Save</button>
            <a href="@Url.Action("Index", "NhaSanXuatAdmin")" class="btn btn-info">Cancel</a>
        </center>
    }
</div>

WebDiDong/Areas/Admin/Views/NhaSanXuatAdmin/Index.cshtml
@model IEnumerable<WebDiDong.Models.NhaSanXuat>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["InfoMessage"] != null)
{
    <div class="alert alert-info">
        <strong>Information : </strong> @TempData["InfoMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
else if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        <strong>Success ! </strong> @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
else if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">NHÀ SẢN XUẤT</h6>
    </div>
    <form style="margin-left: 49px; margin-top: 27px;">
        <label for="search"></label>
        <input type="search"
               class="form-control"
               id="search"
               name="search"
               placeholder="Search"
               style="width: 200px; display: inline;"
               value="@ViewBag.Search" />
        <button type="submit" class="btn btn-primary mx-2">Go</button>
    </form>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã nhà sản xuất</th>
                        <th>Tên nhà sản xuất</th>
                        <th class="text-center" colspan="2">
                            <a href="@Url.Action("Create","NhaSanXuatAdmin")"><img src="~/Asset/images/Add.png" /></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaNhaSanXuat</td>
                            <td>@item.TenNhaSanXuat</td>
                            <td class="text-center" colspan="2">
                                <a href="@Url.Action("Edit","NhaSanXuatAdmin", new { id = @item.MaNhaSanXuat})"> <img src="~/Asset/images/edit.png" /></a> &nbsp;&nbsp;
                                <a href="@Url.Action("Delete","NhaSanXuatAdmin", new { id = @item.MaNhaSanXuat})"> <img src="~/Asset/images/Delete.png" /></a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>



    @{
        int PrevPage = ViewBag.Page - 1;
        if (PrevPage <= 0)
        {
            PrevPage = 1;
        }
        int NextPage = ViewBag.Page + 1;
        if (NextPage > ViewBag.NoOfPages)
        {
            NextPage = ViewBag.NoOfPages;
        }
    }


    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link" href="/Admin/NhaSanXuatAdmin?page=@PrevPage&search=@ViewBag.Search">
                <<
            </a>
        </li>
        @for (int i = 0; i < ViewBag.NoOfPages; i++)
        {
            if (i + 1 == ViewBag.Page)
            {
                <li class="page-item active">
                    <a class="page-link" href="/Admin/NhaSanXuatAdmin?page=@(i+1)&search=@ViewBag.Search">
                        @(i + 1)
                    </a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="/Admin/NhaSanXuatAdmin?page=@(i+1)&search=@ViewBag.Search">
                        @(i + 1)
                    </a>
                </li>
            }
        }
        <li class="page-item">
            <a class="page-link" href="/Admin/NhaSanXuatAdmin?page=@NextPage&search=@ViewBag.Search">
                >>
            </a>
        </li>
    </ul>
</div>