WebDiDong/Areas/Admin/Controllers/SanPhamAdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDiDong.Models;

namespace WebDiDong.Areas.Admin.Controllers
{
    public class SanPhamAdminController : Controller
    {
        [Authorize(Roles = "Admin")]
        // GET: Admin/SanPham
        public ActionResult Index(string search = "", int page = 1)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            List<SanPham> sanPhams = db.SanPhams.Where<SanPham>(row => row.TenSanPham.Contains(search)).ToList();
            ViewBag.Search = search;
            if (sanPhams.Count == 0)
            {
                TempData["InfoMessage"] = "Currently products not available in the Database.";
            }

            //Paging
            int NoOfRecordPerPage = 6;
            int NoOfPages = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(sanPhams.Count) / Convert.ToDouble(NoOfRecordPerPage)));
            int NoOfRecordToSkip = (page - 1) * NoOfRecordPerPage;
            ViewBag.Page = page;
            ViewBag.NoOfPages = NoOfPages;
            sanPhams = sanPhams.Skip(NoOfRecordToSkip).Take(NoOfRecordPerPage).ToList();
            return View(sanPhams);
        }

        // GET: Admin/SanPham/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/SanPham/Create
        public ActionResult Create()
        {
            DBDiDongEntities db = new DBDiDongEntities();

            ViewBag.NSX = db.NhaSanXuats.ToList();
            ViewBag.LSP = db.LoaiSanPhams.ToList();
            return View();
        }

        // POST: Admin/SanPham/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SanPham sp)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    int IsInserted = 0;
                    DBDiDongEntities db = new DBDiDongEntities();


                    //Image
                    string fileName = Path.GetFileNameWithoutExtension(sp.HinHChinhFile.FileName);
                    string extension = Path.GetExtension(sp.HinHChinhFile.FileName);
                    fileName = fileName + extension;
                    sp.HinhChinh = fileName;
                    fileName = Path.Combine(Server.MapPath("~/Asset/images/"), fileName);
                    sp.HinHChinhFile.SaveAs(fileName);


                    sp.LuotView = 0;
                    sp.SoLuongDaBan = 0;
                    sp.GhiChu = "New";
                    db.SanPhams.Add(sp);
                    IsInserted = db.SaveChanges();
                    if (IsInserted == 1)
                    {
                        TempData["SuccessMessage"] = "Bạn đã thêm thành công...!";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Product is already available/ Unable to save the product details.";
                    }
                }

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/SanPham/Edit/5
        public ActionResult Edit(int id)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            SanPham sanPham = db.SanPhams.Where<SanPham>(row => row.MaSanPham == id).FirstOrDefault();
            ViewBag.NSX = db.NhaSanXuats.ToList();
            ViewBag.LSP = db.LoaiSanPhams.ToList();
            if (sanPham == null)
            {
                TempData["InfoMessage"] = "Product not available with ID " + id.ToString();
                return RedirectToAction("Index");
            }
            return View(sanPham);
        }

        // POST: Admin/SanPham/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, SanPham sp)
        {
            try
            {
                int IsUpdate = 0;
                DBDiDongEntities db = new DBDiDongEntities();
                SanPham sanPham = db.SanPhams.Where<SanPham>(row => row.MaSanPham == sp.MaSanPham).FirstOrDefault();
                var tam = sanPham.HinhChinh;

                var test = sp.HinHChinhFile;
                if(test != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(sp.HinHChinhFile.FileName);
                    string extension = Path.GetExtension(sp.HinHChinhFile.FileName);
                    fileName = fileName + extension;
                    sp.HinhChinh = fileName;
                    fileName = Path.Combine(Server.MapPath("~/Asset/images/"), fileName);
                    sp.HinHChinhFile.SaveAs(fileName);

                    sanPham.HinhChinh = sp.HinhChinh;
                }
                else
                {
                    sanPham.HinhChinh = tam;
                }
                //Image
                


                sanPham.MaSanPham = sp.MaSanPham;
                sanPham.TenSanPham = sp.TenSanPham;
                sanPham.MaLoaiSanPham = sp.MaLoaiSanPham;
                sanPham.MaNhaSanXuat = sp.MaNhaSanXuat;

                sanPham.CauHinh = sp.CauHinh;
                sanPham.Gia = sp.Gia;

                IsUpdate = db.SaveChanges();
                if (IsUpdate == 1)
                {
                    TempData["SuccessMessage"] = "Bạn đã cập nhật thành công...!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Product is already available/ Unable to update the product details.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }

        // GET: Admin/SanPham/Delete/5
        public ActionResult Delete(int id)
        {
            DBDiDongEntities db = new DBDiDongEntities();
            SanPham sanPham = db.SanPhams.Where<SanPham>(row => row.MaSanPham == id).FirstOrDefault();
            if (sanPham == null)
            {
                TempData["InfoMessage"] = "Product not available with ID " + id.ToString();
                return RedirectToAction("Index");
            }
            return View(sanPham);
        }

        // POST: Admin/SanPham/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, SanPham sp)
        {
            try
            {
                int IsDeleted = 0;
                DBDiDongEntities db = new DBDiDongEntities();
                SanPham sanPham = db.SanPhams.Where<SanPham>(row => row.MaSanPham == id).FirstOrDefault();
                db.SanPhams.Remove(sanPham);
                IsDeleted = db.SaveChanges();
                if (IsDeleted == 1)
                {
                    TempData["SuccessMessage"] = "Bạn đã xóa thành công...!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Product is already available/ Unable to update the product details.";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View();
            }
            return RedirectToAction("Index");
        }
    }
}

WebDiDong/Areas/Admin/Views/SanPhamAdmin/Create.cshtml
@model WebDiDong.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<style>
    input[type=number], input[type=file], .inputSanPham {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    select {
        margin-bottom: 8px;
    }

    .ck-editor__editable[role="textbox"] {
        /* editing area */
        min-height: 200px;
    }

    .ck-content .image {
        /* block images */
        max-width: 80%;
        margin: 20px auto;
    }

</style>
@using (Html.BeginForm("Create", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table style="display: flex; justify-content: center;">
        <tr>
            <td>Tên Sản Phẩm</td>
        </tr>
        <tr>
            <td> <input class="inputSanPham" type="text" name="TenSanPham" required /></td>
        </tr>
        <tr>
            <td>Loại</td>
        </tr>
        <tr>
            <td>
                <select class="form-select" id="lLoai" name="MaLoaiSanPham">
                    <option value="">Xin hãy chọn...</option>
                    @foreach (var loai in ViewBag.LSP)
                    {
                        <option value="@loai.MaLoaiSanPham">
                            @loai.TenLoaiSanPham
                        </option>
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>Giá</td>
        </tr>
        <tr>
            <td> <input style="width: 300px; float:left;" type="number" name="Gia" required /></td>
        </tr>
        <tr>
            <td>Nhà Sản Xuất</td>
        </tr>
        <tr>
            <td>
                <select class="form-select" id="lbrand" name="MaNhaSanXuat">
                    <option value="">Xin hãy chọn...</option>
                    @foreach (var nsx in ViewBag.NSX)
                    {
                        <option value="@nsx.MaNhaSanXuat">
                            @nsx.TenNhaSanXuat
                        </option>
                    }
                </select>

            </td>
        </tr>
        <tr>
            <td>Hình Chính</td>
        </tr>
        <tr>
            <td>
                <input type="file" id="limage" name="HinHChinhFile" required />

            </td>
        </tr>

        <tr>
            <td>Cấu hình</td>
        </tr>

        <tr>
            <td><textarea  name="CauHinh" id="editor"></textarea></td>
            
        </tr>
        

        <tr>
            <td colspan="3">
                <center>
                    <button type="submit" class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px; ">Create</button>
                    <a href="@Url.Action("Index", "SanPhamAdmin")" class="btn btn-info">Cancel</a>
                </center>
            </td>
        </tr>
    </table>
}

WebDiDong/Areas/Admin/Views/SanPhamAdmin/Delete.cshtml
@model WebDiDong.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<div class="container">
    <h3 class="text-info">Bạn có muốn xóa ?</h3>
    <div>
        <dl class="dl-horizontal">
            <dt>
                Mã sản phẩm:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MaSanPham)
            </dd>

            <dt>
                Tên sản phẩm:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TenSanPham)
            </dd>

            <dt>
                Tên nhà sản xuất:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NhaSanXuat.TenNhaSanXuat)
            </dd>

            <dt>
                Loại:
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSanPham)
            </dd>

            <dt>
                Hình Chính:
            </dt>

            <dd>
                <img src="~/Asset/images/@Model.HinhChinh" style="width:200px;height:200px;">
            </dd>

            <dt>
                Giá:
            </dt>

            <dd>
                @String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:0,0}", Model.Gia) VNĐ
            </dd>


        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <center>
                    <button type="submit" class="btn btn-danger" style="margin-top: 20px; margin-bottom: 20px; ">Delete</button>
                    <a href="@Url.Action("Index", "SanPhamAdmin")" class="btn btn-info" style="margin-top: 20px; margin-bottom: 20px; ">Cancel</a>
                </center>
            </div>
        }
    </div>
</div>

WebDiDong/Areas/Admin/Views/SanPhamAdmin/Edit.cshtml
@model WebDiDong.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<style>
    input[type=number], .inputSanPham {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        flex: 1;
    }

    select {
        margin-bottom: 8px;
    }

    select {
        margin-bottom: 8px;
    }

    .ck-editor__editable[role="textbox"] {
        /* editing area */
        min-height: 200px;
    }

    .ck-content .image {
        /* block images */
        max-width: 80%;
        margin: 20px auto;
    }
</style>
@using (Html.BeginForm("Edit", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table style="display: flex; justify-content: center;">
        <tr>
            <td>Mã Sản Phẩm</td>
        </tr>
        <tr>
            <td> <input class="inputSanPham" type="text" name="MaSanPham" value="@Model.MaSanPham" readonly /></td>
        </tr>
        <tr>
            <td>Tên Sản Phẩm</td>
        </tr>
        <tr>
            <td> <input class="inputSanPham" type="text" name="TenSanPham" value="@Model.TenSanPham" /></td>
        </tr>
        <tr>
            <td>Loại</td>
        </tr>
        <tr>
            <td>
                <select class="form-select" id="lLoai" name="MaLoaiSanPham">
                    <option value="">Xin hãy chọn...</option>
                    @foreach (var loai in ViewBag.LSP)
                    {
                        if (loai.MaLoaiSanPham == Model.MaLoaiSanPham)
                        {
                            <option value="@loai.MaLoaiSanPham" selected>
                                @loai.TenLoaiSanPham
                            </option>
                        }
                        else
                        {
                            <option value="@loai.MaLoaiSanPham">
                                @loai.TenLoaiSanPham
                            </option>
                        }

                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>Giá</td>
        </tr>
        <tr>
            <td> <input style="width: 300px; float:left;" type="number" name="Gia" value="@Model.Gia" /></td>
        </tr>
        <tr>
            <td>Nhà Sản Xuất</td>
        </tr>
        <tr>
            <td>
                <select class="form-select" id="lbrand" name="MaNhaSanXuat">
                    <option value="">Xin hãy chọn...</option>
                    @foreach (var nsx in ViewBag.NSX)
                    {
                        if (nsx.MaNhaSanXuat == Model.MaNhaSanXuat)
                        {
                            <option value="@nsx.MaNhaSanXuat" selected>
                                @nsx.TenNhaSanXuat
                            </option>
                        }
                        else
                        {
                            <option value="@nsx.MaNhaSanXuat">
                                @nsx.TenNhaSanXuat
                            </option>
                        }

                    }
                </select>

            </td>
        </tr>
        <tr>
            <td>Hình Chính</td>
        </tr>
        <tr>
            <td>
                @Model.HinhChinh
                <input type="file" id="limage" name="HinHChinhFile" />
            </td>
        </tr>

        <tr>
            <td>Cấu Hình</td>
        </tr>
        <tr>
            <td><textarea name="CauHinh" id="editor">@Model.CauHinh</textarea></td>
        </tr>

        <tr>
            <td colspan="3">
                <center>
                    <button type="submit" class="btn btn-success" style="margin-top: 20px; margin-bottom: 20px; ">Save</button>
                    <a href="@Url.Action("Index", "SanPhamAdmin")" class="btn btn-info">Cancel</a>
                </center>
            </td>
        </tr>
    </table>
}

WebDiDong/Areas/Admin/Views/SanPhamAdmin/Index.cshtml
@model IEnumerable<WebDiDong.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}

@if (TempData["InfoMessage"] != null)
{
    <div class="alert alert-info">
        <strong>Information : </strong> @TempData["InfoMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
else if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        <strong>Success ! </strong> @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}
else if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong> @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>x</span>
        </button>
    </div>
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">SẢN PHẨM</h6>
    </div>
    <form style="margin-left: 49px; margin-top: 27px;">
        <label for="search"></label>
        <input type="search"
               class="form-control"
               id="search"
               name="search"
               placeholder="Search"
               style="width: 200px; display: inline;"
               value="@ViewBag.Search" />
        <button type="submit" class="btn btn-primary mx-2">Go</button>
    </form>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã sản phẩm</th>
                        <th>Tên sản phẩm</th>
                        <th>Hình Ảnh</th>
                        <th class="text-center" colspan="2">
                            <a href="@Url.Action("Create","SanPhamAdmin")"><img src="~/Asset/images/Add.png" /></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaSanPham</td>
                            <td>@item.TenSanPham</td>
                            <td class="text-center"><img src="~/Asset/images/@item.HinhChinh" style="width:60px;height:60px;"></td>
                            <td class="text-center" colspan="2">
                                <a href="@Url.Action("Edit","SanPhamAdmin", new { id = @item.MaSanPham})"> <img src="~/Asset/images/edit.png" /></a> &nbsp;&nbsp;
                                <a href="@Url.Action("Delete","SanPhamAdmin", new { id = @item.MaSanPham})"> <img src="~/Asset/images/Delete.png" /></a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
    @{
        int PrevPage = ViewBag.Page - 1;
        if (PrevPage <= 0)
        {
            PrevPage = 1;
        }
        int NextPage = ViewBag.Page + 1;
        if (NextPage > ViewBag.NoOfPages)
        {
            NextPage = ViewBag.NoOfPages;
        }
    }


    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link" href="/Admin/SanPhamAdmin?page=@PrevPage&search=@ViewBag.Search">
                <<
            </a>
        </li>
        @for (int i = 0; i < ViewBag.NoOfPages; i++)
        {
            if (i + 1 == ViewBag.Page)
            {
                <li class="page-item active">
                    <a class="page-link" href="/Admin/SanPhamAdmin?page=@(i+1)&search=@ViewBag.Search">
                        @(i + 1)
                    </a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="/Admin/SanPhamAdmin?page=@(i+1)&search=@ViewBag.Search">
                        @(i + 1)
                    </a>
                </li>
            }
        }
        <li class="page-item">
            <a class="page-link" href="/Admin/SanPhamAdmin?page=@NextPage&search=@ViewBag.Search">
                >>
            </a>
        </li>
    </ul>
</div>